### ISSUE TITLE
Parse really long doubles and throw away the extra precision

### ISSUE THREAD

**Issue by amosr** [ambiata/anemone#40]
We should be able to parse really long doubles, but at the moment fail hard on this. An example is `12345678901234567890` which is actually too big to fit in an int64, so we fail hard. In comparison `read "12345678901234567890"` produces the result `1.2345678901234567e19`: note that the last `89` are thrown away.

So the plan to do this:
`anemone_string_to_i64_v128` and `anemone_string_to_i64` should parse the first 19 digits and throw away the rest, but if there are remaining digits return the number of extra ones. We could encode this as a negative error code with the number of digits.

That way the double parsing can check if the digits is > 0 and if so increase the exponent or whatever.

Crazy SSE below:

```
        if (ANEMONE_UNLIKELY(index == 16)) {
            in              += 16;
            m                = anemone_sse_load_bytes128(in, pe);
            index            = anemone_sse_first_nondigit(m);
            if (index > buffer_size) {
                index = buffer_size;
            }
            buffer_size -= index;
            if (ANEMONE_UNLIKELY(index > 3)) {
// At this point we know there are more digits than we can handle, so:
// if index == 16 loop, read again, keep going until we find a non-digit, counting number of extra digits
// if index < 16 we know there are index-3 extra digits
// we should no longer return here, but instead cap index to 3 and perform parsing as usual,
// returning extra digits as error code
                return 1;
            }

            m                        = _mm_subs_epi8(m, zeros);
            const uint64_t i3        = anemone_string_to_i64_v128_first_eight(m, index);
            const uint64_t mul3 = powers_of_ten[index];
            int_out = int_out * mul3 + i3;

        }
```

**Comment by erikd-ambiata** [comment]
So what happens if the string you're parsing is `12345678901234567890e-20` ?

**Comment by amosr** [comment]
We should still be able to drop the last two digits and increase the exponent by two:

```
λ 12345678901234567890e-20
0.12345678901234568

λ 1234567890123456789e-19
0.12345678901234568

λ 123456789012345678e-18
0.12345678901234568

λ 12345678901234567e-17
0.12345678901234566
```

For the fractional part is dropped, I believe we just ignore the dropped digits.

**Comment by erikd-ambiata** [comment]
Ok, that makes sense. Please add me as a reviewer when this is implemented.

**Comment by amosr** [comment]
Ok. I don't think it's high priority right now since we can fall back to attoparsec or strtod

**Comment by erikd-ambiata** [comment]
Well DS has rolled back to a version of Blowfish that uses attoparsec. However that version doesn't give very good error messages (specifically when Blowfish's input data is rubbish). 

I'm happy to work on this if you want. I'd like to see it fixed so DS can use the latest and greatest Blowfish.

FYI, the error message was:
```
Failed parsing index [723] with value ["0.00014574916040285997"] - Failed reading:
    Double cannot be parsed:"0.00014574916040285997"
```

**Comment by jystic** [comment]
> Well DS has rolled back to a version of Blowfish that uses attoparsec. However that version doesn't give very good error messages (specifically when Blowfish's input data is rubbish).
>
> I'm happy to work on this if you want. I'd like to see it fixed so DS can use the latest and greatest Blowfish.

I don't want to rush this through as it's going to be a little fiddly, especially with the SSE implementation, and I want to be able to take our time and get it right.

If this is blocking DS, can we change [walrus](https://github.com/ambiata/walrus/blob/41fce7a2d33cd8500f4f086dadcd51cfea264eee/walrus-core/src/Walrus/Core/Snapshot/Parser.hs#L142) to use [Data.ByteString.Lex.Fractional.readExponential](http://hackage.haskell.org/package/bytestring-lexing-0.5.0.2/docs/Data-ByteString-Lex-Fractional.html#readExponential) or attoparsec in the mean time?

**Comment by erikd-ambiata** [comment]
Its not blocking DS, but they get much poorer error messages until this is fixed.

**Comment by jystic** [comment]
> they get much poorer error messages until this is fixed

I don't see that this particular issue is blocking improved error messages, walrus can be fairly easily changed to use an alternative double parser if you want to upgrade.

`readSigned readExponential` is a drop in replacement for Anenome.parseDouble:
```hs
#!/usr/bin/env mafia

{-# PACKAGE bytestring #-}
{-# PACKAGE bytestring-lexing #-}

{-# LANGUAGE OverloadedStrings #-}

import Data.ByteString.Lex.Fractional

main :: IO ()
main =
  case readSigned readExponential "0.00014574916040285997" of
    Nothing ->
      putStrLn "failed to parse"
    Just (v, rest) ->
      print (v, rest)
```
Output:
```
(1.4574916040285997e-4,"")
```

**Comment by erikd-ambiata** [comment]
Just to make life easier, we'd probably switch back to attoparsec for a short term fix.
